import { createClient } from '@/lib/supabase/server';

/* What belongs in a sitemap.
 *
 * Two rules, and both are about not damaging the thing the sitemap is
 * meant to help.
 *
 * Test records never appear. Nine of the nine venues currently
 * published carry "(Test)" in the name, and submitting them tells Google
 * the collection is nine made-up places.
 *
 * A page with nothing on it never appears. There are 114 practices and
 * 42 have venues; submitting the other 72 is submitting 72 empty pages,
 * which is how a site teaches a crawler that its pages are thin.
 *
 * The pages still exist and still render — they are simply not
 * advertised until there is something on them.
 */

export const SITE = 'https://www.theglobalsanctum.com';

export type Entry = {
  url: string;
  lastModified?: string | Date;
  changeFrequency?: 'always' | 'hourly' | 'daily' | 'weekly' | 'monthly'
                  | 'yearly' | 'never';
  priority?: number;
};

export const STATIC_PAGES: Entry[] = [
  { url: '/', changeFrequency: 'weekly', priority: 1 },
  { url: '/venues', changeFrequency: 'daily', priority: 0.9 },
  { url: '/wellness-experiences', changeFrequency: 'weekly', priority: 0.8 },
  { url: '/the-wellness-edit', changeFrequency: 'weekly', priority: 0.8 },
  { url: '/list-your-venue', changeFrequency: 'monthly', priority: 0.8 },
  { url: '/about', changeFrequency: 'monthly', priority: 0.6 },
  { url: '/how-it-works', changeFrequency: 'monthly', priority: 0.6 },
  { url: '/contact', changeFrequency: 'monthly', priority: 0.5 },
  { url: '/legal', changeFrequency: 'monthly', priority: 0.3 },
];

export async function venueEntries(): Promise<Entry[]> {
  const supabase = await createClient();
  const { data } = await supabase.from('venue_cards')
    .select('listing_slug, marketplace, is_test_record, country_slug, city_slug')
    .eq('is_test_record', false);

  return (data ?? [])
    .filter((v: any) => v.listing_slug)
    .map((v: any) => ({
      url: `/${v.marketplace === 'Wellness' ? 'wellness-venues' : 'retreat-venues'}`
         + `/${v.listing_slug}`,
      changeFrequency: 'weekly' as const,
      priority: 0.7,
    }));
}

/** Country and city pages, from venues that are real and published. */
export async function locationEntries(): Promise<Entry[]> {
  const supabase = await createClient();
  const { data } = await supabase.from('venue_cards')
    .select('country_slug, state_slug, city_slug, is_test_record')
    .eq('is_test_record', false);

  const countries = new Set<string>();
  const cities = new Set<string>();

  for (const v of (data ?? []) as any[]) {
    if (v.country_slug) countries.add(v.country_slug);
    if (v.country_slug && v.city_slug) {
      cities.add(`${v.country_slug}/${v.city_slug}`);
    }
  }

  return [
    ...[...countries].map((c) => ({
      url: `/venues?country=${c}`,
      changeFrequency: 'weekly' as const, priority: 0.6,
    })),
  ];
}

export async function practiceEntries(): Promise<Entry[]> {
  const supabase = await createClient();

  const [{ data: cats }, { data: practices }] = await Promise.all([
    supabase.from('experience_categories').select('slug, venue_count').gt('venue_count', 0),
    supabase.from('experience_practices')
      .select('slug, category_slug, venue_count').gt('venue_count', 0),
  ]);

  return [
    ...(cats ?? []).map((c: any) => ({
      url: `/wellness-experiences/${c.slug}`,
      changeFrequency: 'weekly' as const, priority: 0.7,
    })),
    ...(practices ?? []).filter((p: any) => p.category_slug).map((p: any) => ({
      url: `/wellness-experiences/${p.category_slug}/${p.slug}`,
      changeFrequency: 'weekly' as const, priority: 0.6,
    })),
  ];
}

export async function legalEntries(): Promise<Entry[]> {
  const supabase = await createClient();
  const { data } = await supabase.from('public_legal_documents')
    .select('slug, updated_at, on_legal_page');

  return (data ?? []).map((d: any) => ({
    url: `/legal/${d.slug}`,
    lastModified: d.updated_at ?? undefined,
    changeFrequency: 'yearly' as const,
    // A policy is not something to rank for; it is something to find
    // when looked for.
    priority: d.on_legal_page ? 0.3 : 0.2,
  }));
}

/** Serialises entries as an XML sitemap.
 *
 *  Written rather than generated by the framework, because the six files
 *  robots.txt already names have to exist at those exact paths and
 *  Next's own sitemap route cannot produce arbitrary filenames. */
export function toXml(entries: Entry[]) {
  const urls = entries.map((e) => {
    const loc = `${SITE}${e.url}`
      .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
    const last = e.lastModified
      ? `\n    <lastmod>${new Date(e.lastModified).toISOString().slice(0, 10)}</lastmod>`
      : '';
    const freq = e.changeFrequency
      ? `\n    <changefreq>${e.changeFrequency}</changefreq>` : '';
    const pri = e.priority !== undefined
      ? `\n    <priority>${e.priority.toFixed(1)}</priority>` : '';
    return `  <url>\n    <loc>${loc}</loc>${last}${freq}${pri}\n  </url>`;
  }).join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>\n`
    + `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls}\n</urlset>\n`;
}

export function xmlResponse(body: string) {
  return new Response(body, {
    headers: {
      'content-type': 'application/xml; charset=utf-8',
      // An hour is often enough for a site that gains a venue a day, and
      // it stops a crawler's repeat visit costing a full rebuild.
      'cache-control': 'public, max-age=3600, s-maxage=3600',
    },
  });
}
