import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { createZip, type ZipEntry } from '@/lib/zip';
import { renderPlain } from '@/lib/legalRender';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';
export const maxDuration = 60;

/* ═══════════════════════════════════════════════════════════════════════
   LEGAL COMPLIANCE ARCHIVE

   One file holding everything: the wording of every version, every
   uploaded document, the acceptance records, and a manifest.

   The point is that it should still make sense to somebody in three
   years who has never seen this system — so it carries a README
   explaining what it is, and every folder is named after the document
   slug rather than a database id.
   ═══════════════════════════════════════════════════════════════════════ */

const clean = (s: string) =>
  s.replace(/[^a-zA-Z0-9-_. ]/g, '').replace(/\s+/g, '-').slice(0, 80);

const csvCell = (v: unknown) => {
  const s = v == null ? '' : String(v);
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
};

export async function GET(req: NextRequest) {
  const supabase = await createClient();
  const includeFiles = req.nextUrl.searchParams.get('files') !== 'no';

  const [{ data: docs }, { data: versions }, { data: files },
         { data: acceptances }, { data: settings }] = await Promise.all([
    supabase.from('legal_documents').select('*').order('display_order').order('id'),
    supabase.from('legal_document_versions').select('*')
      .order('legal_document_id').order('effective_from', { nullsFirst: true }),
    supabase.from('legal_files').select('*'),
    supabase.from('legal_acceptances').select('*').limit(20000),
    supabase.from('tgs_settings').select('setting_key,setting_value')
      .eq('setting_group', 'Legal entity'),
  ]);

  const entity = Object.fromEntries(
    (settings ?? []).map((s: any) => [s.setting_key, s.setting_value]));

  const stamp = new Date();
  const dateStr = stamp.toISOString().slice(0, 10);
  const entries: ZipEntry[] = [];

  const versionsFor = (id: number) =>
    (versions ?? []).filter((v: any) => v.legal_document_id === id);
  const filesFor = (id: number) =>
    (files ?? []).filter((f: any) => f.legal_document_id === id);

  /* ── README ─────────────────────────────────────────────────────── */
  entries.push({
    path: 'README.txt',
    data: [
      'THE GLOBAL SANCTUM — LEGAL ARCHIVE',
      `Exported ${stamp.toLocaleString('en-AU')}`,
      '',
      entity.legal_entity_name ?? 'Aurella Group Pty Ltd',
      entity.abn ? `ABN ${entity.abn}` : '',
      entity.registered_address ?? '',
      '',
      'WHAT THIS IS',
      '',
      'A complete copy of every legal document held by The Global Sanctum at',
      'the date above: the wording of every version, the files uploaded',
      'against each document, and the record of who accepted what.',
      '',
      'It is a point-in-time copy. Documents may have been revised since.',
      'The live version is always the one in the portal.',
      '',
      'HOW IT IS ORGANISED',
      '',
      '  manifest.md            every document, its status and its versions',
      '  documents/{slug}/      one folder per document',
      '    document.txt         what it is, who it is for, where it is used',
      '    v-{date}.md          the wording of each version, in Markdown',
      '    v-{date}.txt         the same wording as plain text',
      '  files/{slug}/          PDFs and signed copies as uploaded',
      '  acceptances.csv        who accepted which version, and when',
      '',
      'ON VERSIONS',
      '',
      'A document is never edited in place. When wording changes, the old',
      'version keeps its text and gains an end date. So the file named for',
      'a given date is what was in force on that date — which is what',
      'matters if somebody questions what they agreed to.',
      '',
      `Generated by the TGS internal portal · ${dateStr}`,
    ].join('\n'),
  });

  /* ── manifest ───────────────────────────────────────────────────── */
  const manifest: string[] = [
    '# Legal archive manifest', '',
    `**Exported** ${stamp.toLocaleString('en-AU')}`,
    `**Entity** ${entity.legal_entity_name ?? 'Aurella Group Pty Ltd'}`,
    entity.abn ? `**ABN** ${entity.abn}` : '',
    '', '---', '',
    `${(docs ?? []).length} documents · ${(versions ?? []).length} versions · `
      + `${(files ?? []).length} files · ${(acceptances ?? []).length} acceptances`,
    '',
  ];

  const byCategory = new Map<string, any[]>();
  for (const d of docs ?? []) {
    const cat = d.category ?? 'Uncategorised';
    byCategory.set(cat, [...(byCategory.get(cat) ?? []), d]);
  }

  for (const [cat, list] of byCategory) {
    manifest.push(`## ${cat}`, '');
    manifest.push('| Document | For | Versions | Files | Status |');
    manifest.push('|---|---|---|---|---|');
    for (const d of list) {
      const vs = versionsFor(d.id);
      const current = vs.find((v: any) => v.is_current);
      manifest.push(
        `| ${d.name} | ${d.document_type} | ${vs.length}`
        + `${current ? ` (current from ${current.effective_from ?? '—'})` : ' — none current'}`
        + ` | ${filesFor(d.id).length} | ${d.is_published ? 'Published' : 'Draft'} |`);
    }
    manifest.push('');
  }

  // Anything a reader should know is missing rather than absent by accident.
  const noWording = (docs ?? []).filter((d: any) => !versionsFor(d.id).some((v: any) => v.body));
  if (noWording.length) {
    manifest.push('## Documents with no wording held', '',
      'These exist as records but their text has not been entered. Where a PDF',
      'was uploaded, the wording is in that file rather than in the database.', '');
    for (const d of noWording) manifest.push(`- ${d.name}`);
    manifest.push('');
  }

  entries.push({ path: 'manifest.md', data: manifest.filter(Boolean).join('\n') });

  /* ── each document ──────────────────────────────────────────────── */
  for (const d of docs ?? []) {
    const folder = `documents/${clean(d.slug)}`;

    entries.push({
      path: `${folder}/document.txt`,
      data: [
        d.name,
        '='.repeat(d.name.length), '',
        `Slug            ${d.slug}`,
        `For             ${d.document_type}`,
        `Category        ${d.category ?? '—'}`,
        `Jurisdiction    ${d.jurisdiction ?? '—'}`,
        `Published       ${d.is_published ? 'Yes' : 'Draft'}`,
        `Acceptance      ${d.requires_acceptance ? 'Required' : 'Not required'}`,
        `Review due      ${d.review_due ?? '—'}`,
        '',
        d.summary ? `Summary\n  ${d.summary}` : '',
        (d.used_on ?? []).length ? `\nUsed on\n${(d.used_on ?? []).map((u: string) => `  · ${u}`).join('\n')}` : '',
        d.owner_note ? `\nNote\n  ${d.owner_note}` : '',
      ].filter(Boolean).join('\n'),
    });

    for (const v of versionsFor(d.id)) {
      if (!v.body) continue;
      const label = clean(v.effective_from ?? v.version_label ?? String(v.id));
      const header = [
        `# ${d.name}`, '',
        `Version: ${v.version_label ?? '—'}`,
        `In force from: ${v.effective_from ?? '—'}`,
        `In force to: ${v.effective_to ?? (v.is_current ? 'Current' : '—')}`,
        v.change_summary ? `What changed: ${v.change_summary}` : '',
        v.approved_by ? `Approved by: ${v.approved_by}` : '',
        '', '---', '',
      ].filter(Boolean).join('\n');

      entries.push({ path: `${folder}/v-${label}.md`, data: header + v.body });
      entries.push({ path: `${folder}/v-${label}.txt`,
                     data: renderPlain(header + v.body) });
    }
  }

  /* ── uploaded files ─────────────────────────────────────────────── */
  let fileCount = 0;
  if (includeFiles) {
    for (const f of files ?? []) {
      if (!f.storage_path) continue;
      const doc = (docs ?? []).find((d: any) => d.id === f.legal_document_id);
      try {
        const { data } = await supabase.storage.from('legal').download(f.storage_path);
        if (!data) continue;
        const bytes = new Uint8Array(await data.arrayBuffer());
        entries.push({
          path: `files/${clean(doc?.slug ?? 'unfiled')}/${clean(f.file_name)}`,
          data: bytes,
        });
        fileCount++;
      } catch {
        // A file that cannot be read is noted rather than failing the export.
        entries.push({
          path: `files/${clean(doc?.slug ?? 'unfiled')}/MISSING-${clean(f.file_name)}.txt`,
          data: `This file could not be read from storage at export time.\nPath: ${f.storage_path}`,
        });
      }
    }
  }

  /* ── acceptances ────────────────────────────────────────────────── */
  const acceptanceRows = [
    ['Document', 'Version', 'Accepted by', 'Email', 'Accepted at', 'IP', 'Reference']
      .join(','),
  ];
  for (const a of acceptances ?? []) {
    const doc = (docs ?? []).find((d: any) => d.id === a.legal_document_id);
    const ver = (versions ?? []).find((v: any) => v.id === a.version_id);
    acceptanceRows.push([
      doc?.name, ver?.version_label ?? ver?.effective_from,
      a.accepted_by_name ?? a.accepted_by, a.accepted_by_email,
      a.accepted_at, a.ip_address, a.reference,
    ].map(csvCell).join(','));
  }
  entries.push({ path: 'acceptances.csv', data: acceptanceRows.join('\r\n') });

  /* ── build ──────────────────────────────────────────────────────── */
  const zip = createZip(entries, stamp);
  const fileName = `TGS-legal-archive-${dateStr}.zip`;

  await supabase.from('compliance_exports').insert({
    export_kind: 'Legal',
    documents_count: (docs ?? []).length,
    versions_count: (versions ?? []).length,
    files_count: fileCount,
    acceptances_count: (acceptances ?? []).length,
    file_name: fileName,
    size_bytes: zip.length,
    notes: includeFiles ? null : 'Wording only — uploaded files excluded.',
  });

  await supabase.from('legal_documents')
    .update({ last_exported_at: stamp.toISOString() })
    .not('id', 'is', null);

  return new NextResponse(zip as unknown as BodyInit, {
    headers: {
      'Content-Type': 'application/zip',
      'Content-Disposition': `attachment; filename="${fileName}"`,
      'Content-Length': String(zip.length),
    },
  });
}
